name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.11'  # Use your preferred Julia version
      - name: Build TorchPID package first
        run: |
          julia --project=. -e '
            using Pkg
            Pkg.instantiate()
            Pkg.build("TorchPID")
            Pkg.precompile()'
      - name: Install dependencies
        run: |
          julia --project=docs/ -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          julia --project=docs/ -e '
            using Pkg
            using Documenter
            using TorchPID
            # Force clean build
            rm(joinpath(@__DIR__, "..", "docs", "build"), force=true, recursive=true)
            include("../docs/make.jl")
          '
